-- Add missing columns to proyectos table
ALTER TABLE proyectos 
ADD COLUMN IF NOT EXISTS ambito VARCHAR(50) DEFAULT 'urbano',
ADD COLUMN IF NOT EXISTS tipo_red VARCHAR(50) DEFAULT 'cerrada',
ADD COLUMN IF NOT EXISTS departamento VARCHAR(100),
ADD COLUMN IF NOT EXISTS provincia VARCHAR(100),
ADD COLUMN IF NOT EXISTS distrito VARCHAR(100),
ADD COLUMN IF NOT EXISTS poblacion_diseno INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS periodo_diseno INTEGER DEFAULT 20,
ADD COLUMN IF NOT EXISTS dotacion_percapita FLOAT DEFAULT 169.0,
ADD COLUMN IF NOT EXISTS coef_cobertura FLOAT DEFAULT 0.8,
ADD COLUMN IF NOT EXISTS coef_hazen_williams FLOAT DEFAULT 150.0;
